#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SHOPGIAY")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertTHUONGHIEU(THUONGHIEU instance);
    partial void UpdateTHUONGHIEU(THUONGHIEU instance);
    partial void DeleteTHUONGHIEU(THUONGHIEU instance);
    partial void InsertCTDONDATHANG(CTDONDATHANG instance);
    partial void UpdateCTDONDATHANG(CTDONDATHANG instance);
    partial void DeleteCTDONDATHANG(CTDONDATHANG instance);
    partial void InsertDONDATHANG(DONDATHANG instance);
    partial void UpdateDONDATHANG(DONDATHANG instance);
    partial void DeleteDONDATHANG(DONDATHANG instance);
    partial void InsertGIAMGIA(GIAMGIA instance);
    partial void UpdateGIAMGIA(GIAMGIA instance);
    partial void DeleteGIAMGIA(GIAMGIA instance);
    partial void InsertGIAY(GIAY instance);
    partial void UpdateGIAY(GIAY instance);
    partial void DeleteGIAY(GIAY instance);
    partial void InsertHINH(HINH instance);
    partial void UpdateHINH(HINH instance);
    partial void DeleteHINH(HINH instance);
    partial void InsertKICHTHUOC(KICHTHUOC instance);
    partial void UpdateKICHTHUOC(KICHTHUOC instance);
    partial void DeleteKICHTHUOC(KICHTHUOC instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLOAI(LOAI instance);
    partial void UpdateLOAI(LOAI instance);
    partial void DeleteLOAI(LOAI instance);
    partial void InsertMAUSAC(MAUSAC instance);
    partial void UpdateMAUSAC(MAUSAC instance);
    partial void DeleteMAUSAC(MAUSAC instance);
    partial void InsertPHIEUNHAPKHO(PHIEUNHAPKHO instance);
    partial void UpdatePHIEUNHAPKHO(PHIEUNHAPKHO instance);
    partial void DeletePHIEUNHAPKHO(PHIEUNHAPKHO instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SHOPGIAYConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<THUONGHIEU> THUONGHIEUs
		{
			get
			{
				return this.GetTable<THUONGHIEU>();
			}
		}
		
		public System.Data.Linq.Table<CTDONDATHANG> CTDONDATHANGs
		{
			get
			{
				return this.GetTable<CTDONDATHANG>();
			}
		}
		
		public System.Data.Linq.Table<DONDATHANG> DONDATHANGs
		{
			get
			{
				return this.GetTable<DONDATHANG>();
			}
		}
		
		public System.Data.Linq.Table<GIAMGIA> GIAMGIAs
		{
			get
			{
				return this.GetTable<GIAMGIA>();
			}
		}
		
		public System.Data.Linq.Table<GIAY> GIAYs
		{
			get
			{
				return this.GetTable<GIAY>();
			}
		}
		
		public System.Data.Linq.Table<HINH> HINHs
		{
			get
			{
				return this.GetTable<HINH>();
			}
		}
		
		public System.Data.Linq.Table<KICHTHUOC> KICHTHUOCs
		{
			get
			{
				return this.GetTable<KICHTHUOC>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAI> LOAIs
		{
			get
			{
				return this.GetTable<LOAI>();
			}
		}
		
		public System.Data.Linq.Table<MAUSAC> MAUSACs
		{
			get
			{
				return this.GetTable<MAUSAC>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUNHAPKHO> PHIEUNHAPKHOs
		{
			get
			{
				return this.GetTable<PHIEUNHAPKHO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAADMIN;
		
		private string _HOTEN;
		
		private string _DIACHI;
		
		private string _DIENTHOAI;
		
		private string _TENLOAI;
		
		private string _TENDN;
		
		private string _MATKHAU;
		
		private string _AVATAR;
		
		private string _EMAIL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAADMINChanging(int value);
    partial void OnMAADMINChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnAVATARChanging(string value);
    partial void OnAVATARChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAADMIN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAADMIN
		{
			get
			{
				return this._MAADMIN;
			}
			set
			{
				if ((this._MAADMIN != value))
				{
					this.OnMAADMINChanging(value);
					this.SendPropertyChanging();
					this._MAADMIN = value;
					this.SendPropertyChanged("MAADMIN");
					this.OnMAADMINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVATAR", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string AVATAR
		{
			get
			{
				return this._AVATAR;
			}
			set
			{
				if ((this._AVATAR != value))
				{
					this.OnAVATARChanging(value);
					this.SendPropertyChanging();
					this._AVATAR = value;
					this.SendPropertyChanged("AVATAR");
					this.OnAVATARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUONGHIEU")]
	public partial class THUONGHIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATH;
		
		private string _TENTH;
		
		private string _LOGO;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHChanging(int value);
    partial void OnMATHChanged();
    partial void OnTENTHChanging(string value);
    partial void OnTENTHChanged();
    partial void OnLOGOChanging(string value);
    partial void OnLOGOChanged();
    #endregion
		
		public THUONGHIEU()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATH
		{
			get
			{
				return this._MATH;
			}
			set
			{
				if ((this._MATH != value))
				{
					this.OnMATHChanging(value);
					this.SendPropertyChanging();
					this._MATH = value;
					this.SendPropertyChanged("MATH");
					this.OnMATHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTH", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TENTH
		{
			get
			{
				return this._TENTH;
			}
			set
			{
				if ((this._TENTH != value))
				{
					this.OnTENTHChanging(value);
					this.SendPropertyChanging();
					this._TENTH = value;
					this.SendPropertyChanged("TENTH");
					this.OnTENTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGO", DbType="NVarChar(100)")]
		public string LOGO
		{
			get
			{
				return this._LOGO;
			}
			set
			{
				if ((this._LOGO != value))
				{
					this.OnLOGOChanging(value);
					this.SendPropertyChanging();
					this._LOGO = value;
					this.SendPropertyChanged("LOGO");
					this.OnLOGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUONGHIEU_GIAY", Storage="_GIAYs", ThisKey="MATH", OtherKey="MATH")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.THUONGHIEU = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.THUONGHIEU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTDONDATHANG")]
	public partial class CTDONDATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MADH;
		
		private int _MAGIAY;
		
		private int _SOLUONG;
		
		private int _DONGIA;
		
		private EntityRef<DONDATHANG> _DONDATHANG;
		
		private EntityRef<GIAY> _GIAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADHChanging(int value);
    partial void OnMADHChanged();
    partial void OnMAGIAYChanging(int value);
    partial void OnMAGIAYChanged();
    partial void OnSOLUONGChanging(int value);
    partial void OnSOLUONGChanged();
    partial void OnDONGIAChanging(int value);
    partial void OnDONGIAChanged();
    #endregion
		
		public CTDONDATHANG()
		{
			this._DONDATHANG = default(EntityRef<DONDATHANG>);
			this._GIAY = default(EntityRef<GIAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MADH
		{
			get
			{
				return this._MADH;
			}
			set
			{
				if ((this._MADH != value))
				{
					if (this._DONDATHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADHChanging(value);
					this.SendPropertyChanging();
					this._MADH = value;
					this.SendPropertyChanged("MADH");
					this.OnMADHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAY", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAGIAY
		{
			get
			{
				return this._MAGIAY;
			}
			set
			{
				if ((this._MAGIAY != value))
				{
					if (this._GIAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGIAYChanging(value);
					this.SendPropertyChanging();
					this._MAGIAY = value;
					this.SendPropertyChanged("MAGIAY");
					this.OnMAGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int NOT NULL")]
		public int SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Int NOT NULL")]
		public int DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONDATHANG_CTDONDATHANG", Storage="_DONDATHANG", ThisKey="MADH", OtherKey="MADH", IsForeignKey=true)]
		public DONDATHANG DONDATHANG
		{
			get
			{
				return this._DONDATHANG.Entity;
			}
			set
			{
				DONDATHANG previousValue = this._DONDATHANG.Entity;
				if (((previousValue != value) 
							|| (this._DONDATHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONDATHANG.Entity = null;
						previousValue.CTDONDATHANGs.Remove(this);
					}
					this._DONDATHANG.Entity = value;
					if ((value != null))
					{
						value.CTDONDATHANGs.Add(this);
						this._MADH = value.MADH;
					}
					else
					{
						this._MADH = default(int);
					}
					this.SendPropertyChanged("DONDATHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_CTDONDATHANG", Storage="_GIAY", ThisKey="MAGIAY", OtherKey="MAGIAY", IsForeignKey=true)]
		public GIAY GIAY
		{
			get
			{
				return this._GIAY.Entity;
			}
			set
			{
				GIAY previousValue = this._GIAY.Entity;
				if (((previousValue != value) 
							|| (this._GIAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAY.Entity = null;
						previousValue.CTDONDATHANGs.Remove(this);
					}
					this._GIAY.Entity = value;
					if ((value != null))
					{
						value.CTDONDATHANGs.Add(this);
						this._MAGIAY = value.MAGIAY;
					}
					else
					{
						this._MAGIAY = default(int);
					}
					this.SendPropertyChanged("GIAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONDATHANG")]
	public partial class DONDATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MADH;
		
		private int _MAKH;
		
		private System.DateTime _NGAYDAT;
		
		private System.Nullable<System.DateTime> _NGAYGIAO;
		
		private System.Nullable<bool> _TINHTRANGDH;
		
		private System.Nullable<bool> _DATHANHTOAN;
		
		private EntitySet<CTDONDATHANG> _CTDONDATHANGs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADHChanging(int value);
    partial void OnMADHChanged();
    partial void OnMAKHChanging(int value);
    partial void OnMAKHChanged();
    partial void OnNGAYDATChanging(System.DateTime value);
    partial void OnNGAYDATChanged();
    partial void OnNGAYGIAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYGIAOChanged();
    partial void OnTINHTRANGDHChanging(System.Nullable<bool> value);
    partial void OnTINHTRANGDHChanged();
    partial void OnDATHANHTOANChanging(System.Nullable<bool> value);
    partial void OnDATHANHTOANChanged();
    #endregion
		
		public DONDATHANG()
		{
			this._CTDONDATHANGs = new EntitySet<CTDONDATHANG>(new Action<CTDONDATHANG>(this.attach_CTDONDATHANGs), new Action<CTDONDATHANG>(this.detach_CTDONDATHANGs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MADH
		{
			get
			{
				return this._MADH;
			}
			set
			{
				if ((this._MADH != value))
				{
					this.OnMADHChanging(value);
					this.SendPropertyChanging();
					this._MADH = value;
					this.SendPropertyChanged("MADH");
					this.OnMADHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="Int NOT NULL")]
		public int MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDAT", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYDAT
		{
			get
			{
				return this._NGAYDAT;
			}
			set
			{
				if ((this._NGAYDAT != value))
				{
					this.OnNGAYDATChanging(value);
					this.SendPropertyChanging();
					this._NGAYDAT = value;
					this.SendPropertyChanged("NGAYDAT");
					this.OnNGAYDATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGIAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYGIAO
		{
			get
			{
				return this._NGAYGIAO;
			}
			set
			{
				if ((this._NGAYGIAO != value))
				{
					this.OnNGAYGIAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYGIAO = value;
					this.SendPropertyChanged("NGAYGIAO");
					this.OnNGAYGIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANGDH", DbType="Bit")]
		public System.Nullable<bool> TINHTRANGDH
		{
			get
			{
				return this._TINHTRANGDH;
			}
			set
			{
				if ((this._TINHTRANGDH != value))
				{
					this.OnTINHTRANGDHChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANGDH = value;
					this.SendPropertyChanged("TINHTRANGDH");
					this.OnTINHTRANGDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATHANHTOAN", DbType="Bit")]
		public System.Nullable<bool> DATHANHTOAN
		{
			get
			{
				return this._DATHANHTOAN;
			}
			set
			{
				if ((this._DATHANHTOAN != value))
				{
					this.OnDATHANHTOANChanging(value);
					this.SendPropertyChanging();
					this._DATHANHTOAN = value;
					this.SendPropertyChanged("DATHANHTOAN");
					this.OnDATHANHTOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONDATHANG_CTDONDATHANG", Storage="_CTDONDATHANGs", ThisKey="MADH", OtherKey="MADH")]
		public EntitySet<CTDONDATHANG> CTDONDATHANGs
		{
			get
			{
				return this._CTDONDATHANGs;
			}
			set
			{
				this._CTDONDATHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DONDATHANG", Storage="_KHACHHANG", ThisKey="MAKH", OtherKey="MAKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.DONDATHANGs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.DONDATHANGs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTDONDATHANGs(CTDONDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.DONDATHANG = this;
		}
		
		private void detach_CTDONDATHANGs(CTDONDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.DONDATHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAMGIA")]
	public partial class GIAMGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAGIAMGIA;
		
		private int _MAGIAY;
		
		private int _PHAMTRAMGIAM;
		
		private EntityRef<GIAY> _GIAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAGIAMGIAChanging(int value);
    partial void OnMAGIAMGIAChanged();
    partial void OnMAGIAYChanging(int value);
    partial void OnMAGIAYChanged();
    partial void OnPHAMTRAMGIAMChanging(int value);
    partial void OnPHAMTRAMGIAMChanged();
    #endregion
		
		public GIAMGIA()
		{
			this._GIAY = default(EntityRef<GIAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAMGIA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAGIAMGIA
		{
			get
			{
				return this._MAGIAMGIA;
			}
			set
			{
				if ((this._MAGIAMGIA != value))
				{
					this.OnMAGIAMGIAChanging(value);
					this.SendPropertyChanging();
					this._MAGIAMGIA = value;
					this.SendPropertyChanged("MAGIAMGIA");
					this.OnMAGIAMGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAY", DbType="Int NOT NULL")]
		public int MAGIAY
		{
			get
			{
				return this._MAGIAY;
			}
			set
			{
				if ((this._MAGIAY != value))
				{
					if (this._GIAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGIAYChanging(value);
					this.SendPropertyChanging();
					this._MAGIAY = value;
					this.SendPropertyChanged("MAGIAY");
					this.OnMAGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHAMTRAMGIAM", DbType="Int NOT NULL")]
		public int PHAMTRAMGIAM
		{
			get
			{
				return this._PHAMTRAMGIAM;
			}
			set
			{
				if ((this._PHAMTRAMGIAM != value))
				{
					this.OnPHAMTRAMGIAMChanging(value);
					this.SendPropertyChanging();
					this._PHAMTRAMGIAM = value;
					this.SendPropertyChanged("PHAMTRAMGIAM");
					this.OnPHAMTRAMGIAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_GIAMGIA", Storage="_GIAY", ThisKey="MAGIAY", OtherKey="MAGIAY", IsForeignKey=true)]
		public GIAY GIAY
		{
			get
			{
				return this._GIAY.Entity;
			}
			set
			{
				GIAY previousValue = this._GIAY.Entity;
				if (((previousValue != value) 
							|| (this._GIAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAY.Entity = null;
						previousValue.GIAMGIAs.Remove(this);
					}
					this._GIAY.Entity = value;
					if ((value != null))
					{
						value.GIAMGIAs.Add(this);
						this._MAGIAY = value.MAGIAY;
					}
					else
					{
						this._MAGIAY = default(int);
					}
					this.SendPropertyChanged("GIAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAY")]
	public partial class GIAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAGIAY;
		
		private string _TENGIAY;
		
		private System.Nullable<decimal> _DONGIAMUA;
		
		private System.Nullable<decimal> _DONGIABAN;
		
		private int _MATH;
		
		private int _MALOAI;
		
		private int _MAMAUSAC;
		
		private int _SOLUONG;
		
		private string _HINHANH;
		
		private string _MOTA;
		
		private string _THANHTOANON;
		
		private EntitySet<CTDONDATHANG> _CTDONDATHANGs;
		
		private EntitySet<GIAMGIA> _GIAMGIAs;
		
		private EntitySet<HINH> _HINHs;
		
		private EntitySet<KICHTHUOC> _KICHTHUOCs;
		
		private EntitySet<PHIEUNHAPKHO> _PHIEUNHAPKHOs;
		
		private EntityRef<THUONGHIEU> _THUONGHIEU;
		
		private EntityRef<LOAI> _LOAI;
		
		private EntityRef<MAUSAC> _MAUSAC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAGIAYChanging(int value);
    partial void OnMAGIAYChanged();
    partial void OnTENGIAYChanging(string value);
    partial void OnTENGIAYChanged();
    partial void OnDONGIAMUAChanging(System.Nullable<decimal> value);
    partial void OnDONGIAMUAChanged();
    partial void OnDONGIABANChanging(System.Nullable<decimal> value);
    partial void OnDONGIABANChanged();
    partial void OnMATHChanging(int value);
    partial void OnMATHChanged();
    partial void OnMALOAIChanging(int value);
    partial void OnMALOAIChanged();
    partial void OnMAMAUSACChanging(int value);
    partial void OnMAMAUSACChanged();
    partial void OnSOLUONGChanging(int value);
    partial void OnSOLUONGChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    partial void OnTHANHTOANONChanging(string value);
    partial void OnTHANHTOANONChanged();
    #endregion
		
		public GIAY()
		{
			this._CTDONDATHANGs = new EntitySet<CTDONDATHANG>(new Action<CTDONDATHANG>(this.attach_CTDONDATHANGs), new Action<CTDONDATHANG>(this.detach_CTDONDATHANGs));
			this._GIAMGIAs = new EntitySet<GIAMGIA>(new Action<GIAMGIA>(this.attach_GIAMGIAs), new Action<GIAMGIA>(this.detach_GIAMGIAs));
			this._HINHs = new EntitySet<HINH>(new Action<HINH>(this.attach_HINHs), new Action<HINH>(this.detach_HINHs));
			this._KICHTHUOCs = new EntitySet<KICHTHUOC>(new Action<KICHTHUOC>(this.attach_KICHTHUOCs), new Action<KICHTHUOC>(this.detach_KICHTHUOCs));
			this._PHIEUNHAPKHOs = new EntitySet<PHIEUNHAPKHO>(new Action<PHIEUNHAPKHO>(this.attach_PHIEUNHAPKHOs), new Action<PHIEUNHAPKHO>(this.detach_PHIEUNHAPKHOs));
			this._THUONGHIEU = default(EntityRef<THUONGHIEU>);
			this._LOAI = default(EntityRef<LOAI>);
			this._MAUSAC = default(EntityRef<MAUSAC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAY", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAGIAY
		{
			get
			{
				return this._MAGIAY;
			}
			set
			{
				if ((this._MAGIAY != value))
				{
					this.OnMAGIAYChanging(value);
					this.SendPropertyChanging();
					this._MAGIAY = value;
					this.SendPropertyChanged("MAGIAY");
					this.OnMAGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENGIAY", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENGIAY
		{
			get
			{
				return this._TENGIAY;
			}
			set
			{
				if ((this._TENGIAY != value))
				{
					this.OnTENGIAYChanging(value);
					this.SendPropertyChanging();
					this._TENGIAY = value;
					this.SendPropertyChanged("TENGIAY");
					this.OnTENGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIAMUA", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DONGIAMUA
		{
			get
			{
				return this._DONGIAMUA;
			}
			set
			{
				if ((this._DONGIAMUA != value))
				{
					this.OnDONGIAMUAChanging(value);
					this.SendPropertyChanging();
					this._DONGIAMUA = value;
					this.SendPropertyChanged("DONGIAMUA");
					this.OnDONGIAMUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIABAN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DONGIABAN
		{
			get
			{
				return this._DONGIABAN;
			}
			set
			{
				if ((this._DONGIABAN != value))
				{
					this.OnDONGIABANChanging(value);
					this.SendPropertyChanging();
					this._DONGIABAN = value;
					this.SendPropertyChanged("DONGIABAN");
					this.OnDONGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATH", DbType="Int NOT NULL")]
		public int MATH
		{
			get
			{
				return this._MATH;
			}
			set
			{
				if ((this._MATH != value))
				{
					if (this._THUONGHIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHChanging(value);
					this.SendPropertyChanging();
					this._MATH = value;
					this.SendPropertyChanged("MATH");
					this.OnMATHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Int NOT NULL")]
		public int MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					if (this._LOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMAUSAC", DbType="Int NOT NULL")]
		public int MAMAUSAC
		{
			get
			{
				return this._MAMAUSAC;
			}
			set
			{
				if ((this._MAMAUSAC != value))
				{
					if (this._MAUSAC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAMAUSACChanging(value);
					this.SendPropertyChanging();
					this._MAMAUSAC = value;
					this.SendPropertyChanged("MAMAUSAC");
					this.OnMAMAUSACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int NOT NULL")]
		public int SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(100)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTOANON", DbType="NVarChar(200)")]
		public string THANHTOANON
		{
			get
			{
				return this._THANHTOANON;
			}
			set
			{
				if ((this._THANHTOANON != value))
				{
					this.OnTHANHTOANONChanging(value);
					this.SendPropertyChanging();
					this._THANHTOANON = value;
					this.SendPropertyChanged("THANHTOANON");
					this.OnTHANHTOANONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_CTDONDATHANG", Storage="_CTDONDATHANGs", ThisKey="MAGIAY", OtherKey="MAGIAY")]
		public EntitySet<CTDONDATHANG> CTDONDATHANGs
		{
			get
			{
				return this._CTDONDATHANGs;
			}
			set
			{
				this._CTDONDATHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_GIAMGIA", Storage="_GIAMGIAs", ThisKey="MAGIAY", OtherKey="MAGIAY")]
		public EntitySet<GIAMGIA> GIAMGIAs
		{
			get
			{
				return this._GIAMGIAs;
			}
			set
			{
				this._GIAMGIAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_HINH", Storage="_HINHs", ThisKey="MAGIAY", OtherKey="MAGIAY")]
		public EntitySet<HINH> HINHs
		{
			get
			{
				return this._HINHs;
			}
			set
			{
				this._HINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_KICHTHUOC", Storage="_KICHTHUOCs", ThisKey="MAGIAY", OtherKey="MAGIAY")]
		public EntitySet<KICHTHUOC> KICHTHUOCs
		{
			get
			{
				return this._KICHTHUOCs;
			}
			set
			{
				this._KICHTHUOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_PHIEUNHAPKHO", Storage="_PHIEUNHAPKHOs", ThisKey="MAGIAY", OtherKey="MAGIAY")]
		public EntitySet<PHIEUNHAPKHO> PHIEUNHAPKHOs
		{
			get
			{
				return this._PHIEUNHAPKHOs;
			}
			set
			{
				this._PHIEUNHAPKHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUONGHIEU_GIAY", Storage="_THUONGHIEU", ThisKey="MATH", OtherKey="MATH", IsForeignKey=true)]
		public THUONGHIEU THUONGHIEU
		{
			get
			{
				return this._THUONGHIEU.Entity;
			}
			set
			{
				THUONGHIEU previousValue = this._THUONGHIEU.Entity;
				if (((previousValue != value) 
							|| (this._THUONGHIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUONGHIEU.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._THUONGHIEU.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MATH = value.MATH;
					}
					else
					{
						this._MATH = default(int);
					}
					this.SendPropertyChanged("THUONGHIEU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_GIAY", Storage="_LOAI", ThisKey="MALOAI", OtherKey="MALOAI", IsForeignKey=true)]
		public LOAI LOAI
		{
			get
			{
				return this._LOAI.Entity;
			}
			set
			{
				LOAI previousValue = this._LOAI.Entity;
				if (((previousValue != value) 
							|| (this._LOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAI.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._LOAI.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MALOAI = value.MALOAI;
					}
					else
					{
						this._MALOAI = default(int);
					}
					this.SendPropertyChanged("LOAI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAUSAC_GIAY", Storage="_MAUSAC", ThisKey="MAMAUSAC", OtherKey="MAMAUSAC", IsForeignKey=true)]
		public MAUSAC MAUSAC
		{
			get
			{
				return this._MAUSAC.Entity;
			}
			set
			{
				MAUSAC previousValue = this._MAUSAC.Entity;
				if (((previousValue != value) 
							|| (this._MAUSAC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAUSAC.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._MAUSAC.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MAMAUSAC = value.MAMAUSAC;
					}
					else
					{
						this._MAMAUSAC = default(int);
					}
					this.SendPropertyChanged("MAUSAC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTDONDATHANGs(CTDONDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = this;
		}
		
		private void detach_CTDONDATHANGs(CTDONDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = null;
		}
		
		private void attach_GIAMGIAs(GIAMGIA entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = this;
		}
		
		private void detach_GIAMGIAs(GIAMGIA entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = null;
		}
		
		private void attach_HINHs(HINH entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = this;
		}
		
		private void detach_HINHs(HINH entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = null;
		}
		
		private void attach_KICHTHUOCs(KICHTHUOC entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = this;
		}
		
		private void detach_KICHTHUOCs(KICHTHUOC entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = null;
		}
		
		private void attach_PHIEUNHAPKHOs(PHIEUNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = this;
		}
		
		private void detach_PHIEUNHAPKHOs(PHIEUNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HINH")]
	public partial class HINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHINH;
		
		private int _MAGIAY;
		
		private string _HINH1;
		
		private EntityRef<GIAY> _GIAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHINHChanging(int value);
    partial void OnMAHINHChanged();
    partial void OnMAGIAYChanging(int value);
    partial void OnMAGIAYChanged();
    partial void OnHINH1Changing(string value);
    partial void OnHINH1Changed();
    #endregion
		
		public HINH()
		{
			this._GIAY = default(EntityRef<GIAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHINH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAHINH
		{
			get
			{
				return this._MAHINH;
			}
			set
			{
				if ((this._MAHINH != value))
				{
					this.OnMAHINHChanging(value);
					this.SendPropertyChanging();
					this._MAHINH = value;
					this.SendPropertyChanged("MAHINH");
					this.OnMAHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAY", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAGIAY
		{
			get
			{
				return this._MAGIAY;
			}
			set
			{
				if ((this._MAGIAY != value))
				{
					if (this._GIAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGIAYChanging(value);
					this.SendPropertyChanging();
					this._MAGIAY = value;
					this.SendPropertyChanged("MAGIAY");
					this.OnMAGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH1", DbType="NVarChar(100)")]
		public string HINH1
		{
			get
			{
				return this._HINH1;
			}
			set
			{
				if ((this._HINH1 != value))
				{
					this.OnHINH1Changing(value);
					this.SendPropertyChanging();
					this._HINH1 = value;
					this.SendPropertyChanged("HINH1");
					this.OnHINH1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_HINH", Storage="_GIAY", ThisKey="MAGIAY", OtherKey="MAGIAY", IsForeignKey=true)]
		public GIAY GIAY
		{
			get
			{
				return this._GIAY.Entity;
			}
			set
			{
				GIAY previousValue = this._GIAY.Entity;
				if (((previousValue != value) 
							|| (this._GIAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAY.Entity = null;
						previousValue.HINHs.Remove(this);
					}
					this._GIAY.Entity = value;
					if ((value != null))
					{
						value.HINHs.Add(this);
						this._MAGIAY = value.MAGIAY;
					}
					else
					{
						this._MAGIAY = default(int);
					}
					this.SendPropertyChanged("GIAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KICHTHUOC")]
	public partial class KICHTHUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAKICHTHUOC;
		
		private int _MAGIAY;
		
		private int _TENKICHTHUOC;
		
		private EntityRef<GIAY> _GIAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKICHTHUOCChanging(int value);
    partial void OnMAKICHTHUOCChanged();
    partial void OnMAGIAYChanging(int value);
    partial void OnMAGIAYChanged();
    partial void OnTENKICHTHUOCChanging(int value);
    partial void OnTENKICHTHUOCChanged();
    #endregion
		
		public KICHTHUOC()
		{
			this._GIAY = default(EntityRef<GIAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKICHTHUOC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAKICHTHUOC
		{
			get
			{
				return this._MAKICHTHUOC;
			}
			set
			{
				if ((this._MAKICHTHUOC != value))
				{
					this.OnMAKICHTHUOCChanging(value);
					this.SendPropertyChanging();
					this._MAKICHTHUOC = value;
					this.SendPropertyChanged("MAKICHTHUOC");
					this.OnMAKICHTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAY", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAGIAY
		{
			get
			{
				return this._MAGIAY;
			}
			set
			{
				if ((this._MAGIAY != value))
				{
					if (this._GIAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGIAYChanging(value);
					this.SendPropertyChanging();
					this._MAGIAY = value;
					this.SendPropertyChanged("MAGIAY");
					this.OnMAGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKICHTHUOC", DbType="Int NOT NULL")]
		public int TENKICHTHUOC
		{
			get
			{
				return this._TENKICHTHUOC;
			}
			set
			{
				if ((this._TENKICHTHUOC != value))
				{
					this.OnTENKICHTHUOCChanging(value);
					this.SendPropertyChanging();
					this._TENKICHTHUOC = value;
					this.SendPropertyChanged("TENKICHTHUOC");
					this.OnTENKICHTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_KICHTHUOC", Storage="_GIAY", ThisKey="MAGIAY", OtherKey="MAGIAY", IsForeignKey=true)]
		public GIAY GIAY
		{
			get
			{
				return this._GIAY.Entity;
			}
			set
			{
				GIAY previousValue = this._GIAY.Entity;
				if (((previousValue != value) 
							|| (this._GIAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAY.Entity = null;
						previousValue.KICHTHUOCs.Remove(this);
					}
					this._GIAY.Entity = value;
					if ((value != null))
					{
						value.KICHTHUOCs.Add(this);
						this._MAGIAY = value.MAGIAY;
					}
					else
					{
						this._MAGIAY = default(int);
					}
					this.SendPropertyChanged("GIAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAKH;
		
		private string _HOTENKH;
		
		private string _DIENTHOAI;
		
		private string _DIACHI;
		
		private string _TENDNKH;
		
		private string _MATKHAUKH;
		
		private string _EMAIL;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _HINHANH;
		
		private string _KHOIPHUCMATKHAU;
		
		private EntitySet<DONDATHANG> _DONDATHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHChanging(int value);
    partial void OnMAKHChanged();
    partial void OnHOTENKHChanging(string value);
    partial void OnHOTENKHChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnTENDNKHChanging(string value);
    partial void OnTENDNKHChanged();
    partial void OnMATKHAUKHChanging(string value);
    partial void OnMATKHAUKHChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnKHOIPHUCMATKHAUChanging(string value);
    partial void OnKHOIPHUCMATKHAUChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._DONDATHANGs = new EntitySet<DONDATHANG>(new Action<DONDATHANG>(this.attach_DONDATHANGs), new Action<DONDATHANG>(this.detach_DONDATHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENKH", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string HOTENKH
		{
			get
			{
				return this._HOTENKH;
			}
			set
			{
				if ((this._HOTENKH != value))
				{
					this.OnHOTENKHChanging(value);
					this.SendPropertyChanging();
					this._HOTENKH = value;
					this.SendPropertyChanged("HOTENKH");
					this.OnHOTENKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(200)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDNKH", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TENDNKH
		{
			get
			{
				return this._TENDNKH;
			}
			set
			{
				if ((this._TENDNKH != value))
				{
					this.OnTENDNKHChanging(value);
					this.SendPropertyChanging();
					this._TENDNKH = value;
					this.SendPropertyChanged("TENDNKH");
					this.OnTENDNKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAUKH", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MATKHAUKH
		{
			get
			{
				return this._MATKHAUKH;
			}
			set
			{
				if ((this._MATKHAUKH != value))
				{
					this.OnMATKHAUKHChanging(value);
					this.SendPropertyChanging();
					this._MATKHAUKH = value;
					this.SendPropertyChanged("MATKHAUKH");
					this.OnMATKHAUKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(200)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHOIPHUCMATKHAU", DbType="NChar(100)")]
		public string KHOIPHUCMATKHAU
		{
			get
			{
				return this._KHOIPHUCMATKHAU;
			}
			set
			{
				if ((this._KHOIPHUCMATKHAU != value))
				{
					this.OnKHOIPHUCMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._KHOIPHUCMATKHAU = value;
					this.SendPropertyChanged("KHOIPHUCMATKHAU");
					this.OnKHOIPHUCMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DONDATHANG", Storage="_DONDATHANGs", ThisKey="MAKH", OtherKey="MAKH")]
		public EntitySet<DONDATHANG> DONDATHANGs
		{
			get
			{
				return this._DONDATHANGs;
			}
			set
			{
				this._DONDATHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DONDATHANGs(DONDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_DONDATHANGs(DONDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAI")]
	public partial class LOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALOAI;
		
		private string _TENLOAI;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIChanging(int value);
    partial void OnMALOAIChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    #endregion
		
		public LOAI()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_GIAY", Storage="_GIAYs", ThisKey="MALOAI", OtherKey="MALOAI")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAI = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAUSAC")]
	public partial class MAUSAC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAMAUSAC;
		
		private string _TENMAUSAC;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAMAUSACChanging(int value);
    partial void OnMAMAUSACChanged();
    partial void OnTENMAUSACChanging(string value);
    partial void OnTENMAUSACChanged();
    #endregion
		
		public MAUSAC()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMAUSAC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAMAUSAC
		{
			get
			{
				return this._MAMAUSAC;
			}
			set
			{
				if ((this._MAMAUSAC != value))
				{
					this.OnMAMAUSACChanging(value);
					this.SendPropertyChanging();
					this._MAMAUSAC = value;
					this.SendPropertyChanged("MAMAUSAC");
					this.OnMAMAUSACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENMAUSAC", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TENMAUSAC
		{
			get
			{
				return this._TENMAUSAC;
			}
			set
			{
				if ((this._TENMAUSAC != value))
				{
					this.OnTENMAUSACChanging(value);
					this.SendPropertyChanging();
					this._TENMAUSAC = value;
					this.SendPropertyChanged("TENMAUSAC");
					this.OnTENMAUSACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAUSAC_GIAY", Storage="_GIAYs", ThisKey="MAMAUSAC", OtherKey="MAMAUSAC")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.MAUSAC = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.MAUSAC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUNHAPKHO")]
	public partial class PHIEUNHAPKHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPHIEUNK;
		
		private System.DateTime _NGAYNK;
		
		private int _MAGIAY;
		
		private int _SOLUONG;
		
		private EntityRef<GIAY> _GIAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUNKChanging(int value);
    partial void OnMAPHIEUNKChanged();
    partial void OnNGAYNKChanging(System.DateTime value);
    partial void OnNGAYNKChanged();
    partial void OnMAGIAYChanging(int value);
    partial void OnMAGIAYChanged();
    partial void OnSOLUONGChanging(int value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public PHIEUNHAPKHO()
		{
			this._GIAY = default(EntityRef<GIAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUNK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPHIEUNK
		{
			get
			{
				return this._MAPHIEUNK;
			}
			set
			{
				if ((this._MAPHIEUNK != value))
				{
					this.OnMAPHIEUNKChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUNK = value;
					this.SendPropertyChanged("MAPHIEUNK");
					this.OnMAPHIEUNKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNK", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYNK
		{
			get
			{
				return this._NGAYNK;
			}
			set
			{
				if ((this._NGAYNK != value))
				{
					this.OnNGAYNKChanging(value);
					this.SendPropertyChanging();
					this._NGAYNK = value;
					this.SendPropertyChanged("NGAYNK");
					this.OnNGAYNKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAY", DbType="Int NOT NULL")]
		public int MAGIAY
		{
			get
			{
				return this._MAGIAY;
			}
			set
			{
				if ((this._MAGIAY != value))
				{
					if (this._GIAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGIAYChanging(value);
					this.SendPropertyChanging();
					this._MAGIAY = value;
					this.SendPropertyChanged("MAGIAY");
					this.OnMAGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int NOT NULL")]
		public int SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_PHIEUNHAPKHO", Storage="_GIAY", ThisKey="MAGIAY", OtherKey="MAGIAY", IsForeignKey=true)]
		public GIAY GIAY
		{
			get
			{
				return this._GIAY.Entity;
			}
			set
			{
				GIAY previousValue = this._GIAY.Entity;
				if (((previousValue != value) 
							|| (this._GIAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAY.Entity = null;
						previousValue.PHIEUNHAPKHOs.Remove(this);
					}
					this._GIAY.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPKHOs.Add(this);
						this._MAGIAY = value.MAGIAY;
					}
					else
					{
						this._MAGIAY = default(int);
					}
					this.SendPropertyChanged("GIAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
